[build]
builder = "NIXPACKS"

[deploy]
# Pas de startCommand - le script s'ex√©cute uniquement via le cron
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[cron]]
schedule = "15 09 * * *"
command = "node src/index.js"